# Python Stack Review
Python is a great general-purpose programming language on its own, but with the help of a few popular libraries (numpy, scipy, matplotlib) it becomes a powerful environment for scientific computing.

Python tutorial https://docs.python.org/3/tutorial/

## Topics:


In [3]:
# Lambda function
# <funtion name> <arg1>, <arg2>, ... = <function expression>
f = lambda x: x ** 2
print(f(2))

4


### Numpy librarie
Documentation - https://numpy.org/doc/stable/user/index.html#user

Quickstart - https://numpy.org/doc/stable/user/quickstart.html

In [4]:
import numpy as np

In [ ]:
# 3 rolls of 20 dice
dados = np.random.multinomial(20, [1/6.]*6, size=3)
alturas = np.random.normal(180, 15, size = (3,6))
np.set_printoptions(precision=2)
print(dados, alturas, alturas.T, alturas.ravel(), "", sep = "\n\n")

[[3 2 4 3 2 6]
 [3 2 2 5 5 3]
 [2 2 6 3 4 3]]

[[163.97 179.12 168.47 176.45 178.64 190.77]
 [179.35 173.34 176.77 173.93 188.18 190.16]
 [193.24 182.66 175.92 158.18 157.96 149.27]]

[[163.97 179.35 193.24]
 [179.12 173.34 182.66]
 [168.47 176.77 175.92]
 [176.45 173.93 158.18]
 [178.64 188.18 157.96]
 [190.77 190.16 149.27]]

[163.97 179.12 168.47 176.45 178.64 190.77 179.35 173.34 176.77 173.93
 188.18 190.16 193.24 182.66 175.92 158.18 157.96 149.27]




### Numpy librarie
Documentation - https://numpy.org/doc/stable/user/index.html#user

Quickstart - https://numpy.org/doc/stable/user/quickstart.html

## References:
https://cs231n.github.io/python-numpy-tutorial/